name: Build plugin

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Cache local Maven repository
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - run: mvn compile
    - run: mvn hpi:hpi
    - run: ls -la target
    - run: >
        curl
        -H "Max-Days: 1"
        --upload-file target/jenkins-build-export.hpi
        https://transfer.sh/jenkins-build-export.hpi
    - uses: actions/upload-artifact@v3
      with:
        name: plugin
        path: target/jenkins-build-export.hpi
